name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JDK_VERSION: 21
  JDK_DISTRIBUTION: temurin
  NODE_VERSION: 20

jobs:
  playwright_tests:
    timeout-minutes: 30
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy
    steps:
      - name: 🔻 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "${{ env.JDK_DISTRIBUTION }}"
          java-version: "${{ env.JDK_VERSION }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew test
        env:
          PLAYWRIGHT_HEADLESS: "true"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: build/reports
          retention-days: 5