name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker Compose
        working-directory: ./docker
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          while ! docker-compose exec -T timecoder-api curl -f http://localhost:8089; do
            echo "Waiting for timecoder-api..."
            sleep 5
          done
        working-directory: ./docker
        env:
          DOCKER_HOST: tcp://localhost:2375

      - name: Run tests
        run: ./gradlew test

      - name: Shut down Docker Compose
        if: always()
        working-directory: ./docker
        run: docker-compose down